### ISSUE TITLE
Can't use Project Tango Plugin to pack on UE version 4.11.2!

### ISSUE THREAD

**Issue by ZinniaSun2000** [opaquemultimedia/ProjectTangoPlugin#1]
I downloaded the Project Tango Plugin you provided and there's some error during compiling. Then I changed code TangoPointsComponent.h , deleted the "override" at the end of line 183, and changed "RF_RootSet" to "RF_MarkAsRootSet" in line 149 of TangoDevice.cpp. Finally it could be compiled. But when I pack the project, There were still some error notifications. Is this caused because of the Unreal version that we use? If yes, when will you update the plugin to adapt UE 4.11.2? Or could you please tell me how to use this plug-in on Unreal Engine 4.11.2?

**Comment by Micador** [comment]
Hi ZinniaSun2000,

Thanks for listing this! We are currently preparing a 4.11 compatible build and should have that version available shortly.

**Comment by ZinniaSun2000** [comment]
Thanks for reply! When will it be ok?

**Comment by batoulomeus** [comment]
Hi there, 
anything new for 4.11.2 or plans for the new 4.12?
Awesome work you do!

**Comment by Micador** [comment]
Hi all,
Sorry for the late reply! We've been in touch with the Tango team in relation to a bug we're seeing in the Mira release- we've confirmed there is an issue in the current Tango Core (Mira), which is causing the RGB images to display incorrectly. A fix is incoming in the next version of the TangoCore, and we'll be releasing an updated plugin version with 4.12 support ASAP. Thanks for your patience!

**Comment by masterofshapes** [comment]
Great to hear and thanks for making this available to us unreal users. I know you said ASAP and I'm in no way trying to rush you but do you have a rough estimate of dates that you think the update for 4.12 support will be available?

**Comment by muojp** [comment]
https://developers.google.com/tango/release-notes

> Release Notes 
> June 6, 2016: Okul

Okul release is finally there stating `A regression causing the color camera texture to be incorrect in some cases has been fixed.`! 🏆

**Comment by Micador** [comment]
Hi everyone! Thanks so much for your patience!

I'm pleased to say we have an update for you today- there is now a new plugin and example content version uploaded to the Develop branch, for UE4.12 and the Okul Tango Core. This update features a host of improvements including bugfixes and examples for point finding, in-engine tutorials, improvements to A.R. performance and synchronisation, usability improvements and more (please see the changelog in the Example Content project for more details).

With the Okul release of the Tango Core, the A.R. Camera is back to full function- a really big thank you to the Tango team for tracking this down for us.

Please note that there is one known issue (inability to set runtime depth rate to zero after it has been switched on) which has been observed with the version in Develop. We've chosen to push it out ASAP for early adopters before we finalise the merge to Master and the host the new packages on the opaque.media website (ETA within 7 days). 

Please don't hesitate to reach out should you experience any difficulties in upgrading, and we'll do our best to assist. Happy coding!

**Comment by Micador** [comment]
A quick update: we've pushed the latest released plugin version to Master, in both this repository and the Example Content. This issue should now be fixed, and I'll be marking this question as closed for tracking purposes. Please get in touch should if issue still appears when using this latest version.
